### PR TITLE
Allow external server

### PR DESCRIPTION
**Pull request by jgrigg**
These changes were mainly to allow me to run against a provider that i spin up myself (rather than passing an Express/Koa/Restify 'app').

Also done a bit of refactoring here and there and may have introduced breaking changes particularly around the throwing of Errors rather than weird looking objects. The test suite doesn't exactly fill me with confidence :(

@ychua I'm hopeful that this will somehow end up in npmjs (or the just the seek npm repo). It looks like it's been left by the wayside for some time so I'm not holding my breath.

### CODE REVIEW

**Comment by ychua** [comment]
Looks good to me @jgrigg As discussed, if you the pact tests in dashboard-experience-api passes with this PR (backward compatible) and other teams are aware of this change, go merge!

**Comment by ychua** [comment]
Looping David Porter in @davidporter-id-au, David is the maintainer of SEEK/pactjs0 on npm (https://www.npmjs.com/package/nodejs-pact-provider).

**Comment by davidporter-id-au** [comment]
oh, yeah, that's me

**Comment by davidporter-id-au** [comment]
I'll push, assuming I can remember my npm creds

**Comment by davidporter-id-au** [comment]
@ychua I don't have write access on this repo. Would you mind including me

**Comment by jgrigg** [comment]
Thanks @ychua got distracted all day but will get to it an let you know :) @davidporter-id-au I just made you admin. Reckon we could push to npmjs post merge?

**Comment by jgrigg** [comment]
@ychua All the dashboard-experience-api providers pacts are happy against this branch :)
Note I had a bit of trouble getting it to run - ended up fixing it with one of these `npm install bunyan-rotating-file-stream`. Perhaps this needs to be saved in package.json?

**Comment by ychua** [comment]
@davidporter-id-au I'm not an admin myself, Mr @davidduffett might be able to help?

**Comment by ychua** [comment]
@jgrigg nice!

I don't recall having that problem before. If you still have that branch in dashboard-experience-api (without bunyan-rotating-file-stream ), I can kick off a TC build see if pass.

**Pull request merged**
